name: mobwear
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider: ^3.2.0
  toast: ^0.1.5
  line_awesome_icons: ^1.0.4+2
  flip_card: ^0.4.4
  http: ^0.12.0+2
  fonoapi_dart: ^0.1.2+2
  path_provider: ^1.5.1
  flutter_hsvcolor_picker: ^0.0.1
  matrix_gesture_detector: ^0.1.0
  esys_flutter_share: ^1.0.2
  keyboard_visibility: ^0.5.6
  flutter_circle_color_picker: ^0.1.1
  device_preview: ^0.2.6
  flutter_swiper: ^1.1.6
  device_id: ^0.2.0
  package_info: ^0.4.0+13
  hive: ^1.3.0
  hive_flutter: ^0.3.0+1
  flutter_slidable: ^0.5.4
  save_in_gallery: ^0.1.3
  showcaseview: ^0.1.5
  flutter_staggered_grid_view: ^0.3.0
  url_launcher: ^5.4.2
  flushbar: ^1.9.1
  firebase_storage: ^3.1.3
  firebase_core: ^0.4.4+3
  firebase_analytics: ^5.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.0
  build_runner:



flutter:
  uses-material-design: true

  assets:
   - assets/images/
   - assets/textures/

  fonts:
    - family: Righteous
      fonts:
        - asset: assets/fonts/Righteous-Regular.ttf
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Black.ttf
    - family: Archivo
      fonts:
        - asset: assets/fonts/Archivo-Regular.ttf
    - family: BrandIcons
      fonts:
        - asset: assets/fonts/BrandIcons.ttf
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf