name: mobwear
description: A smartphone customization app.
version: 0.1.0+160000100

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider: ^4.1.0
  toast: ^0.1.5
  line_awesome_icons: ^1.0.4+2
  http: ^0.12.1
  fonoapi_dart: ^0.1.3
  path_provider: ^1.6.7
  matrix_gesture_detector: ^0.1.0
  esys_flutter_share: ^1.0.2
  flutter_keyboard_visibility: ^2.0.0
  flutter_circle_color_picker: ^0.1.1
  package_info: ^0.4.0+17
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  flutter_slidable: ^0.5.4
  flutter_staggered_grid_view: ^0.3.0
  url_launcher: ^5.4.5
  flushbar: ^1.10.0
  firebase_storage: ^3.1.5
  firebase_core: ^0.4.4+3
  firebase_analytics: ^5.0.11 
  device_preview: ^0.4.5
  flip: ^1.0.0
  flutter_hsvcolor_picker:
    # path: /mnt/B6F6BF9AF6BF5977/Dee/Documents/Flutter Projects/forks/flutter_hsvcolor_picker
    git: git://github.com/thearthurdev/flutter_hsvcolor_picker
  carousel_slider:
    path: /mnt/B6F6BF9AF6BF5977/Dee/Documents/Flutter Projects/forks/flutter_carousel_slider

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.0+2
  build_runner:

dependency_overrides:
  dartx: ^0.3.0

flutter:
  uses-material-design: true

  assets:
   - assets/images/
   - assets/textures/

  fonts:
    - family: Righteous
      fonts:
        - asset: assets/fonts/Righteous-Regular.ttf
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Black.ttf
    - family: Archivo
      fonts:
        - asset: assets/fonts/Archivo-Regular.ttf
    - family: BrandIcons
      fonts:
        - asset: assets/fonts/BrandIcons.ttf
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
